### ISSUE TITLE
Problem with Signing in a Creating Accounts

### ISSUE THREAD

**Issue by rtarson** [creativetimofficial/argon-dashboard-nodejs#1]
Hi,

I have been trying to install your dashboard using npm does not work. I get stuck at doing `npm knex migrate:latest`.

So instead I have installed yarn was able to use that successfully. But now I have it running and it render the pages all okay. But when it comes to functionality it is not working. I just installed so not really sure really sure where to dig in first to fix. Or if it is because I am using yarn. 

Here is the error I am getting when I preform password change, register user, login, etc...
Note* In my postgresdb it does show that the users that I created were created.

```
TypeError: Cannot set property 'messages' of undefined
    at createUser (/home/rtarson/www/my.aquazen.io/public_html/features/register/commands/create-user.js:18:24)
```

**Comment by Ray-Sutton** [comment]
Hi! I'm actually having an issue logging in. The database is seeded and I checked it so I know the users are there, but I'm not able to log in. I've removed the auth from the routes for the moment so I can do some production testing, but any help would be amazing

**Comment by brownpaint** [comment]
I purchased the PRO version and came up against similar issue when trying to login 

TypeError: Cannot set property 'messages' of undefined

But my error message points to the file: verify-request-body.js

**Comment by MwSpaceLLC** [comment]
Today i have same problem, but fix as follow =)

![image](https://user-images.githubusercontent.com/29952045/70853995-185f4780-1eb6-11ea-83ea-dfd6c5687dfe.png)

If the session stored on redis, but u not configure the session storage. system can't save the session.
simple, now work perfect!! 

![image](https://user-images.githubusercontent.com/29952045/70854024-7a1fb180-1eb6-11ea-8758-ca4bb133d362.png)

![image](https://user-images.githubusercontent.com/29952045/70854020-68d6a500-1eb6-11ea-83de-c02981a5369d.png)

**Comment by brittni27** [comment]
thanks @MwSpaceLLC this worked for me!

**Comment by sanket9192** [comment]
@MwSpaceLLC i tried the above code that you wrote in app.js. it is giving the following error.

Error: secret option required for sessions
    at session (/Users/sanketpatel/WebstormProjects/argon-dashboard-nodejs/node_modules/express-session/index.js:200:12)
    at Layer.handle [as handle_request] (/Users/sanketpatel/WebstormProjects/argon-dashboard-nodejs/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/sanketpatel/WebstormProjects/argon-dashboard-nodejs/node_modules/express/lib/router/index.js:317:13)
    at /Users/sanketpatel/WebstormProjects/argon-dashboard-nodejs/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/sanketpatel/WebstormProjects/argon-dashboard-nodejs/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/sanketpatel/WebstormProjects/argon-dashboard-nodejs/node_modules/express/lib/router/index.js:275:10)
    at SendStream.error (/Users/sanketpatel/WebstormProjects/argon-dashboard-nodejs/node_modules/serve-static/index.js:121:7)
    at SendStream.emit (events.js:310:20)
    at SendStream.error (/Users/sanketpatel/WebstormProjects/argon-dashboard-nodejs/node_modules/send/index.js:270:17)
    at SendStream.onStatError (/Users/sanketpatel/WebstormProjects/argon-dashboard-nodejs/node_modules/send/index.js:421:12)
    at next (/Users/sanketpatel/WebstormProjects/argon-dashboard-nodejs/node_modules/send/index.js:764:28)
    at /Users/sanketpatel/WebstormProjects/argon-dashboard-nodejs/node_modules/send/index.js:772:23
    at FSReqCallback.oncomplete (fs.js:167:21)

**Comment by sanket9192** [comment]
Solved the error. I have to remove the RedisStore configuration from app.js.

**Comment by mufaawan** [comment]
Anyfix for the problem without removing RadisStore configuraitons?

**Comment by Ray-Sutton** [comment]
Here's my app.js file, and my RedisStore function works fine. Make sure you install the npm package as well. 
[app.js.zip](https://github.com/creativetimofficial/argon-dashboard-nodejs/files/4852509/app.js.zip)
